<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Mdaresna.IntegrationContracts\Mdaresna.IntegrationContracts.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Mdaresna.Tenancy.Abstractions\Mdaresna.Tenancy.Abstractions.csproj" />
  </ItemGroup>

</Project>
