// <auto-generated />
using System;
using Mdaresna.Platform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mdaresna.Platform.Infrastructure.Persistence.PostgreSql.Migrations.Platform
{
    [DbContext(typeof(PostgreSqlPlatformDbContext))]
    partial class PostgreSqlPlatformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mdaresna.Platform.Domain.Access.PlatformRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("roles", "access", t =>
                        {
                            t.HasCheckConstraint("ck_access_roles_timestamps", "\"CreatedAtUtc\" <= \"UpdatedAtUtc\" AND TRUE AND TRUE");

                            t.HasCheckConstraint("ck_access_roles_version", "\"Version\" >= 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Access.PlatformRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid>("AssignedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("RevokedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("AccountId", "RevokedAtUtc");

                    b.HasIndex("AccountId", "RoleId")
                        .IsUnique()
                        .HasFilter("\"RevokedAtUtc\" IS NULL");

                    b.ToTable("role_assignments", "access", t =>
                        {
                            t.HasCheckConstraint("ck_access_role_assignments_revocation", "(\"RevokedAtUtc\" IS NULL AND \"RevokedByAccountId\" IS NULL) OR (\"RevokedAtUtc\" IS NOT NULL AND \"RevokedByAccountId\" IS NOT NULL AND \"RevokedAtUtc\" >= \"AssignedAtUtc\")");

                            t.HasCheckConstraint("ck_access_role_assignments_timestamps", "TRUE AND (\"RevokedAtUtc\" IS NULL OR TRUE)");

                            t.HasCheckConstraint("ck_access_role_assignments_version", "\"Version\" >= 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.PlatformPaymentLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("PaymentRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PostedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid>("PostedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransferReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentRequestId")
                        .IsUnique();

                    b.HasIndex("SchoolId", "PostedAtUtc");

                    b.HasIndex("PaymentRequestId", "TenantId", "SchoolId", "Amount", "Currency", "TransferReference");

                    b.ToTable("school_platform_payment_ledger", "billing", t =>
                        {
                            t.HasTrigger("tr_billing_payment_ledger_append_only");

                            t.HasTrigger("tr_billing_payment_ledger_approved_insert");

                            t.HasCheckConstraint("ck_billing_payment_ledger_amount", "\"Amount\" > 0");

                            t.HasCheckConstraint("ck_billing_payment_ledger_currency", "\"Currency\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_billing_payment_ledger_identifiers", "\"Id\" <> '00000000-0000-0000-0000-000000000000' AND \"PaymentRequestId\" <> '00000000-0000-0000-0000-000000000000' AND \"PostedByAccountId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_billing_payment_ledger_posted_utc", "TRUE");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.PlatformPaymentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid>("RequestedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("ReviewedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransferReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "TenantId", "SchoolId", "Amount", "Currency", "TransferReference")
                        .HasName("AK_school_platform_payment_requests_Id_TenantId_SchoolId_Amou~1");

                    b.HasIndex("SchoolId", "TransferReference")
                        .IsUnique();

                    b.HasIndex("TenantId", "SchoolId");

                    b.HasIndex("TenantId", "Status", "RequestedAtUtc");

                    b.ToTable("school_platform_payment_requests", "billing", t =>
                        {
                            t.HasTrigger("tr_billing_payment_request_approved_guard");

                            t.HasCheckConstraint("ck_billing_payment_request_amount", "\"Amount\" > 0");

                            t.HasCheckConstraint("ck_billing_payment_request_currency", "\"Currency\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_billing_payment_request_identifiers", "\"Id\" <> '00000000-0000-0000-0000-000000000000' AND \"RequestedByAccountId\" <> '00000000-0000-0000-0000-000000000000' AND (\"ReviewedByAccountId\" IS NULL OR \"ReviewedByAccountId\" <> '00000000-0000-0000-0000-000000000000')");

                            t.HasCheckConstraint("ck_billing_payment_request_review", "(\"Status\" = 'Pending' AND \"ReviewedByAccountId\" IS NULL AND \"ReviewedAtUtc\" IS NULL AND \"ReviewNote\" IS NULL) OR (\"Status\" IN ('Approved', 'Rejected') AND \"ReviewedByAccountId\" IS NOT NULL AND \"ReviewedAtUtc\" IS NOT NULL AND \"ReviewedAtUtc\" >= \"RequestedAtUtc\" AND \"ReviewedByAccountId\" <> \"RequestedByAccountId\" AND (\"Status\" = 'Approved' OR (\"ReviewNote\" IS NOT NULL AND length(btrim(\"ReviewNote\")) > 0)))");

                            t.HasCheckConstraint("ck_billing_payment_request_status", "\"Status\" IN ('Pending', 'Approved', 'Rejected')");

                            t.HasCheckConstraint("ck_billing_payment_request_timestamps", "TRUE AND (\"ReviewedAtUtc\" IS NULL OR TRUE)");

                            t.HasCheckConstraint("ck_billing_payment_request_version", "\"Version\" >= 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.Units.UnitGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("PaymentMethodCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("PaymentRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("TransferOccurredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("TransferReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("UnitTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UnitTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentRequestId")
                        .IsUnique();

                    b.HasIndex("SchoolId", "GrantedAtUtc");

                    b.HasIndex("PaymentRequestId", "TenantId", "SchoolId", "Amount", "Currency", "TransferReference");

                    b.HasIndex("PaymentRequestId", "TenantId", "SchoolId", "UnitTypeId", "UnitTypeCode", "UnitTypeName", "UnitPrice", "Currency", "Quantity", "Amount", "PaymentMethodCode", "TransferOccurredAtUtc");

                    b.ToTable("unit_grants", "billing", t =>
                        {
                            t.HasTrigger("tr_billing_unit_grant_append_only");

                            t.HasTrigger("tr_billing_unit_grant_approved_insert");

                            t.HasCheckConstraint("ck_billing_unit_grant_currency", "\"Currency\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_billing_unit_grant_granted_utc", "TRUE AND TRUE AND \"TransferOccurredAtUtc\" <= \"GrantedAtUtc\"");

                            t.HasCheckConstraint("ck_billing_unit_grant_ids", "\"Id\" <> '00000000-0000-0000-0000-000000000000' AND \"PaymentRequestId\" <> '00000000-0000-0000-0000-000000000000' AND \"UnitTypeId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_billing_unit_grant_name", "length(btrim(\"UnitTypeName\")) > 0");

                            t.HasCheckConstraint("ck_billing_unit_grant_payment_method", "length(\"PaymentMethodCode\") BETWEEN 3 AND 40 AND \"PaymentMethodCode\" = LOWER(\"PaymentMethodCode\")");

                            t.HasCheckConstraint("ck_billing_unit_grant_price", "\"UnitPrice\" > 0 AND \"Amount\" > 0 AND \"Amount\" = \"UnitPrice\" * \"Quantity\"");

                            t.HasCheckConstraint("ck_billing_unit_grant_quantity", "\"Quantity\" BETWEEN 1 AND 1000000");

                            t.HasCheckConstraint("ck_billing_unit_grant_school", "\"SchoolId\" = \"TenantId\"");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.Units.UnitPurchaseIntent", b =>
                {
                    b.Property<Guid>("PaymentRequestId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("PaymentMethodCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("TransferOccurredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("UnitTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UnitTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("UnitTypeVersion")
                        .HasColumnType("bigint");

                    b.HasKey("PaymentRequestId");

                    b.HasIndex("UnitTypeId");

                    b.HasIndex("SchoolId", "CreatedAtUtc");

                    b.HasIndex("PaymentRequestId", "TenantId", "SchoolId", "Amount", "Currency");

                    b.ToTable("unit_purchase_intents", "billing", t =>
                        {
                            t.HasTrigger("tr_billing_unit_purchase_intent_append_only");

                            t.HasTrigger("tr_billing_unit_purchase_intent_pending_insert");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_code", "length(\"UnitTypeCode\") BETWEEN 3 AND 32 AND \"UnitTypeCode\" = UPPER(\"UnitTypeCode\")");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_created_utc", "TRUE AND TRUE AND \"TransferOccurredAtUtc\" <= \"CreatedAtUtc\"");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_currency", "\"Currency\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_ids", "\"PaymentRequestId\" <> '00000000-0000-0000-0000-000000000000' AND \"UnitTypeId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_name", "length(btrim(\"UnitTypeName\")) > 0");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_payment_method", "length(\"PaymentMethodCode\") BETWEEN 3 AND 40 AND \"PaymentMethodCode\" = LOWER(\"PaymentMethodCode\")");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_price", "\"UnitPrice\" > 0 AND \"Amount\" > 0 AND \"Amount\" = \"UnitPrice\" * \"Quantity\"");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_quantity", "\"Quantity\" BETWEEN 1 AND 1000000");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_school", "\"SchoolId\" = \"TenantId\"");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_version", "\"UnitTypeVersion\" >= 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.Units.UnitType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("unit_types", "billing", t =>
                        {
                            t.HasCheckConstraint("ck_billing_unit_type_code", "length(\"Code\") BETWEEN 3 AND 32 AND \"Code\" = UPPER(\"Code\")");

                            t.HasCheckConstraint("ck_billing_unit_type_currency", "\"Currency\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_billing_unit_type_id", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_billing_unit_type_name", "length(btrim(\"DisplayName\")) > 0");

                            t.HasCheckConstraint("ck_billing_unit_type_price", "\"UnitPrice\" > 0");

                            t.HasCheckConstraint("ck_billing_unit_type_timestamps", "\"CreatedAtUtc\" <= \"UpdatedAtUtc\" AND TRUE AND TRUE");

                            t.HasCheckConstraint("ck_billing_unit_type_version", "\"Version\" >= 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Registry.SchoolDatabaseEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("CredentialSecretReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequireTls")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("SchemaVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Purpose", "IsPrimary")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\" = TRUE");

                    b.HasIndex("SchoolId", "Purpose", "Status");

                    b.HasIndex("SchoolId", "Host", "Port", "DatabaseName")
                        .IsUnique();

                    b.ToTable("school_database_endpoints", "registry", t =>
                        {
                            t.HasCheckConstraint("ck_registry_school_database_endpoints_port", "\"Port\" >= 1 AND \"Port\" <= 65535");

                            t.HasCheckConstraint("ck_registry_school_database_endpoints_provider", "\"Provider\" IN ('PostgreSql', 'SqlServer')");

                            t.HasCheckConstraint("ck_registry_school_database_endpoints_purpose", "\"Purpose\" IN ('Operational', 'Reporting', 'Archive', 'ReadReplica')");

                            t.HasCheckConstraint("ck_registry_school_database_endpoints_retired_primary", "\"Status\" <> 'Retired' OR \"IsPrimary\" = FALSE");

                            t.HasCheckConstraint("ck_registry_school_database_endpoints_status", "\"Status\" IN ('Provisioning', 'Active', 'Unavailable', 'Retired')");

                            t.HasCheckConstraint("ck_registry_school_database_endpoints_timestamps", "\"CreatedAtUtc\" <= \"UpdatedAtUtc\" AND TRUE AND TRUE");

                            t.HasCheckConstraint("ck_registry_school_database_endpoints_version", "\"Version\" >= 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Registry.SchoolRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("DeploymentMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ProvisioningOperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistrationRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UnitTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProvisioningOperationId")
                        .IsUnique()
                        .HasFilter("\"ProvisioningOperationId\" IS NOT NULL");

                    b.HasIndex("RegistrationRequestId")
                        .IsUnique();

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.HasIndex("UnitTypeId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("schools", "registry", t =>
                        {
                            t.HasCheckConstraint("ck_registry_schools_deployment_matches_type", "\"DeploymentMode\" <> 'GovernmentOnPremises' OR \"SchoolType\" = 'Government'");

                            t.HasCheckConstraint("ck_registry_schools_deployment_mode", "\"DeploymentMode\" IN ('SharedSaaS', 'DedicatedCloud', 'GovernmentOnPremises')");

                            t.HasCheckConstraint("ck_registry_schools_provisioning_operation", "(\"Status\" IN ('Draft', 'PendingVerification', 'Approved') AND \"ProvisioningOperationId\" IS NULL) OR (\"Status\" IN ('Provisioning', 'ProvisioningFailed', 'Active', 'Suspended') AND \"ProvisioningOperationId\" IS NOT NULL AND \"ProvisioningOperationId\" <> '00000000-0000-0000-0000-000000000000') OR (\"Status\" = 'Closed' AND (\"ProvisioningOperationId\" IS NULL OR \"ProvisioningOperationId\" <> '00000000-0000-0000-0000-000000000000'))");

                            t.HasCheckConstraint("ck_registry_schools_school_is_tenant", "\"Id\" = \"TenantId\"");

                            t.HasCheckConstraint("ck_registry_schools_status", "\"Status\" IN ('Draft', 'PendingVerification', 'Approved', 'Provisioning', 'ProvisioningFailed', 'Active', 'Suspended', 'Closed')");

                            t.HasCheckConstraint("ck_registry_schools_status_reason", "(\"Status\" IN ('ProvisioningFailed', 'Suspended', 'Closed') AND \"StatusReason\" IS NOT NULL AND length(btrim(\"StatusReason\")) > 0) OR (\"Status\" IN ('Draft', 'PendingVerification', 'Approved', 'Provisioning', 'Active') AND \"StatusReason\" IS NULL)");

                            t.HasCheckConstraint("ck_registry_schools_timestamps", "\"CreatedAtUtc\" <= \"UpdatedAtUtc\" AND TRUE AND TRUE");

                            t.HasCheckConstraint("ck_registry_schools_type", "\"SchoolType\" IN ('Private', 'Government')");

                            t.HasCheckConstraint("ck_registry_schools_version", "\"Version\" >= 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Registry.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LegalName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("tenants", "registry", t =>
                        {
                            t.HasCheckConstraint("ck_registry_tenants_status", "\"Status\" IN ('Draft', 'Active', 'Suspended', 'Closed')");

                            t.HasCheckConstraint("ck_registry_tenants_status_reason", "(\"Status\" IN ('Suspended', 'Closed') AND \"SuspensionReason\" IS NOT NULL AND length(btrim(\"SuspensionReason\")) > 0) OR (\"Status\" IN ('Draft', 'Active') AND \"SuspensionReason\" IS NULL)");

                            t.HasCheckConstraint("ck_registry_tenants_timestamps", "\"CreatedAtUtc\" <= \"UpdatedAtUtc\" AND TRUE AND TRUE");

                            t.HasCheckConstraint("ck_registry_tenants_version", "\"Version\" >= 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.ExternalIdentifierMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("InternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("EntityType", "InternalId");

                    b.HasIndex("SourceSystem", "EntityType", "ExternalId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL");

                    b.HasIndex("TenantId", "SourceSystem", "EntityType", "ExternalId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.ToTable("external_id_mappings", "registry", t =>
                        {
                            t.HasCheckConstraint("ck_registry_external_id_mappings_created_utc", "TRUE");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "OccurredAtUtc");

                    b.HasIndex("ResourceType", "ResourceId");

                    b.HasIndex("TenantId", "OccurredAtUtc");

                    b.ToTable("audit_entries", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_operations_audit_entries_occurred_utc", "TRUE");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformFeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.ToTable("feature_flags", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_operations_feature_flags_timestamps", "\"CreatedAtUtc\" <= \"UpdatedAtUtc\" AND TRUE AND TRUE");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformInboxMessage", b =>
                {
                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.HasKey("Consumer", "MessageId");

                    b.HasIndex("ProcessedAtUtc", "ReceivedAtUtc")
                        .HasFilter("\"ProcessedAtUtc\" IS NULL");

                    b.ToTable("inbox_messages", "messaging", t =>
                        {
                            t.HasCheckConstraint("ck_messaging_platform_inbox_timestamps", "TRUE AND (\"ProcessedAtUtc\" IS NULL OR (\"ProcessedAtUtc\" >= \"ReceivedAtUtc\" AND TRUE))");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<int>("FailedSignInCount")
                        .HasColumnType("integer");

                    b.Property<string>("HashingAlgorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("HashingVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.ToTable("local_credentials", "access", t =>
                        {
                            t.HasCheckConstraint("ck_access_local_credentials_failed_count", "\"FailedSignInCount\" >= 0");

                            t.HasCheckConstraint("ck_access_local_credentials_hashing_version", "\"HashingVersion\" > 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalPasswordResetChallenge", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastSentAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("SendCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SendWindowStartUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.HasKey("UserId");

                    b.ToTable("local_password_reset_challenges", "access", t =>
                        {
                            t.HasCheckConstraint("ck_access_local_password_reset_attempts", "\"SendCount\" >= 0 AND \"FailedAttempts\" >= 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("local_users", "access", t =>
                        {
                            t.HasCheckConstraint("ck_access_local_users_identifiers", "\"Id\" <> '00000000-0000-0000-0000-000000000000' AND \"PersonId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_access_local_users_status", "\"Status\" IN ('PendingActivation', 'Active', 'Disabled')");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BodyAr")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("BodyEn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("notifications", "messaging", t =>
                        {
                            t.HasCheckConstraint("ck_messaging_notifications_timestamps", "TRUE AND (\"ExpiresAtUtc\" IS NULL OR (\"ExpiresAtUtc\" > \"CreatedAtUtc\" AND TRUE))");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformNotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("FcmTokenSnapshot")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId", "DeviceId")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAtUtc", "CreatedAtUtc");

                    b.ToTable("notification_deliveries", "messaging", t =>
                        {
                            t.HasCheckConstraint("ck_messaging_notification_deliveries_attempts", "\"AttemptCount\" >= 0");

                            t.HasCheckConstraint("ck_messaging_notification_deliveries_status", "\"Status\" IN ('Pending','Sent','Failed','Skipped')");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformNotificationRecipient", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.HasKey("NotificationId", "AccountId");

                    b.HasIndex("AccountId", "ReadAtUtc", "CreatedAtUtc");

                    b.ToTable("notification_recipients", "messaging", t =>
                        {
                            t.HasCheckConstraint("ck_messaging_notification_recipients_timestamps", "TRUE AND (\"ReadAtUtc\" IS NULL OR (\"ReadAtUtc\" >= \"CreatedAtUtc\" AND TRUE))");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc")
                        .HasFilter("\"ProcessedAtUtc\" IS NULL");

                    b.ToTable("outbox_messages", "messaging", t =>
                        {
                            t.HasCheckConstraint("ck_messaging_platform_outbox_timestamps", "TRUE AND (\"ProcessedAtUtc\" IS NULL OR (\"ProcessedAtUtc\" >= \"OccurredAtUtc\" AND TRUE)) AND (\"NextAttemptAtUtc\" IS NULL OR (\"NextAttemptAtUtc\" >= \"OccurredAtUtc\" AND TRUE))");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformPermissionRecord", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Code");

                    b.ToTable("permissions", "access");

                    b.HasData(
                        new
                        {
                            Code = "platform.schools.read"
                        },
                        new
                        {
                            Code = "platform.schools.manage"
                        },
                        new
                        {
                            Code = "platform.schools.activate"
                        },
                        new
                        {
                            Code = "platform.access.manage"
                        },
                        new
                        {
                            Code = "platform.billing.read"
                        },
                        new
                        {
                            Code = "platform.billing.manage"
                        },
                        new
                        {
                            Code = "platform.payments.approve"
                        },
                        new
                        {
                            Code = "platform.support.manage"
                        },
                        new
                        {
                            Code = "platform.deployments.manage"
                        },
                        new
                        {
                            Code = "platform.audit.read"
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformRolePermissionRecord", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RoleId", "PermissionCode");

                    b.HasIndex("PermissionCode");

                    b.ToTable("role_permissions", "access");
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformSmsLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("MessageEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipientEncrypted")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RecipientMasked")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ResponseEncrypted")
                        .HasColumnType("text");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ProviderId", "CreatedAtUtc");

                    b.HasIndex("SourceSystem", "SourceMessageId")
                        .IsUnique()
                        .HasFilter("\"SourceMessageId\" IS NOT NULL");

                    b.HasIndex("SourceSystem", "SchoolId", "CreatedAtUtc");

                    b.ToTable("sms_logs", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_platform_sms_logs_completion", "(\"Status\" = 'Pending' AND \"CompletedAtUtc\" IS NULL) OR (\"Status\" <> 'Pending' AND \"CompletedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_platform_sms_logs_http_status", "\"HttpStatusCode\" IS NULL OR \"HttpStatusCode\" BETWEEN 100 AND 599");

                            t.HasCheckConstraint("ck_platform_sms_logs_school_scope", "\"SourceSystem\" <> 'schools' OR \"SchoolId\" IS NOT NULL");

                            t.HasCheckConstraint("ck_platform_sms_logs_source_system", "\"SourceSystem\" IN ('platform', 'schools', 'family')");

                            t.HasCheckConstraint("ck_platform_sms_logs_status", "\"Status\" IN ('Pending', 'Accepted', 'Rejected', 'Failed')");

                            t.HasCheckConstraint("ck_platform_sms_logs_timestamps", "TRUE AND (\"CompletedAtUtc\" IS NULL OR (\"CompletedAtUtc\" >= \"CreatedAtUtc\" AND TRUE))");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformSmsProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ApiUrlTemplate")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MessageCharactersLength")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderUserName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SuccessResponsePrefix")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted", "IsActive", "Priority");

                    b.ToTable("sms_providers", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_platform_sms_providers_api_url_https", "\"ApiUrlTemplate\" LIKE 'https://%'");

                            t.HasCheckConstraint("ck_platform_sms_providers_deleted_inactive", "\"IsDeleted\" = FALSE OR \"IsActive\" = FALSE");

                            t.HasCheckConstraint("ck_platform_sms_providers_message_length", "\"MessageCharactersLength\" BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("ck_platform_sms_providers_priority", "\"Priority\" >= 1");

                            t.HasCheckConstraint("ck_platform_sms_providers_timestamps", "\"CreatedAtUtc\" <= \"UpdatedAtUtc\" AND TRUE AND TRUE");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformStaffInvitationChallenge", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastSentAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("SendCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SendWindowStartUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.HasKey("UserId");

                    b.ToTable("staff_invitation_challenges", "access", t =>
                        {
                            t.HasCheckConstraint("ck_access_staff_invitation_attempts", "\"SendCount\" >= 0 AND \"FailedAttempts\" >= 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformUserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FcmToken")
                        .IsUnique();

                    b.HasIndex("AccountId", "InstallationId")
                        .IsUnique();

                    b.HasIndex("AccountId", "LastSeenAtUtc");

                    b.ToTable("user_devices", "messaging", t =>
                        {
                            t.HasCheckConstraint("ck_messaging_user_devices_language", "\"LanguageCode\" IN ('ar','en')");

                            t.HasCheckConstraint("ck_messaging_user_devices_platform", "\"Platform\" IN ('android','ios','web')");

                            t.HasCheckConstraint("ck_messaging_user_devices_timestamps", "\"CreatedAtUtc\" <= \"UpdatedAtUtc\" AND \"UpdatedAtUtc\" <= \"LastSeenAtUtc\" AND TRUE AND TRUE AND TRUE");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Access.PlatformRoleAssignment", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Access.PlatformRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.PlatformPaymentLedgerEntry", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Billing.PlatformPaymentRequest", null)
                        .WithMany()
                        .HasForeignKey("PaymentRequestId", "TenantId", "SchoolId", "Amount", "Currency", "TransferReference")
                        .HasPrincipalKey("Id", "TenantId", "SchoolId", "Amount", "Currency", "TransferReference")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.PlatformPaymentRequest", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Registry.SchoolRegistration", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SchoolId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.Units.UnitGrant", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Billing.PlatformPaymentRequest", null)
                        .WithMany()
                        .HasForeignKey("PaymentRequestId", "TenantId", "SchoolId", "Amount", "Currency", "TransferReference")
                        .HasPrincipalKey("Id", "TenantId", "SchoolId", "Amount", "Currency", "TransferReference")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mdaresna.Platform.Domain.Billing.Units.UnitPurchaseIntent", null)
                        .WithMany()
                        .HasForeignKey("PaymentRequestId", "TenantId", "SchoolId", "UnitTypeId", "UnitTypeCode", "UnitTypeName", "UnitPrice", "Currency", "Quantity", "Amount", "PaymentMethodCode", "TransferOccurredAtUtc")
                        .HasPrincipalKey("PaymentRequestId", "TenantId", "SchoolId", "UnitTypeId", "UnitTypeCode", "UnitTypeName", "UnitPrice", "Currency", "Quantity", "Amount", "PaymentMethodCode", "TransferOccurredAtUtc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.Units.UnitPurchaseIntent", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Billing.Units.UnitType", null)
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mdaresna.Platform.Domain.Billing.PlatformPaymentRequest", null)
                        .WithMany()
                        .HasForeignKey("PaymentRequestId", "TenantId", "SchoolId", "Amount", "Currency")
                        .HasPrincipalKey("Id", "TenantId", "SchoolId", "Amount", "Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Registry.SchoolDatabaseEndpoint", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Registry.SchoolRegistration", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Registry.SchoolRegistration", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Registry.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mdaresna.Platform.Domain.Billing.Units.UnitType", null)
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.ExternalIdentifierMapping", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Registry.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformFeatureFlag", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Registry.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalCredential", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalUser", "User")
                        .WithOne("Credential")
                        .HasForeignKey("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalPasswordResetChallenge", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalUser", "User")
                        .WithOne("PasswordResetChallenge")
                        .HasForeignKey("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalPasswordResetChallenge", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformNotificationDelivery", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformNotification", null)
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformNotificationRecipient", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformNotification", null)
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformRolePermissionRecord", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformPermissionRecord", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mdaresna.Platform.Domain.Access.PlatformRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformSmsLog", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformSmsProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformStaffInvitationChallenge", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalUser", "User")
                        .WithOne("StaffInvitationChallenge")
                        .HasForeignKey("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformStaffInvitationChallenge", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalUser", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("PasswordResetChallenge");

                    b.Navigation("StaffInvitationChallenge");
                });
#pragma warning restore 612, 618
        }
    }
}
