// <auto-generated />
using System;
using Mdaresna.Platform.Infrastructure.Persistence.Platform;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mdaresna.Platform.Infrastructure.Persistence.Platform.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260913212224_AddScopedLocalUsersAndSharedPersonProfile")]
    partial class AddScopedLocalUsersAndSharedPersonProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mdaresna.Platform.Domain.Access.PlatformRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("roles", "access", t =>
                        {
                            t.HasCheckConstraint("ck_access_roles_timestamps", "[CreatedAtUtc] <= [UpdatedAtUtc] AND DATEPART(TZOFFSET, [CreatedAtUtc]) = 0 AND DATEPART(TZOFFSET, [UpdatedAtUtc]) = 0");

                            t.HasCheckConstraint("ck_access_roles_version", "[Version] >= 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Access.PlatformRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<Guid>("AssignedByAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<Guid?>("RevokedByAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("AccountId", "RevokedAtUtc");

                    b.HasIndex("AccountId", "RoleId")
                        .IsUnique()
                        .HasFilter("[RevokedAtUtc] IS NULL");

                    b.ToTable("role_assignments", "access", t =>
                        {
                            t.HasCheckConstraint("ck_access_role_assignments_revocation", "([RevokedAtUtc] IS NULL AND [RevokedByAccountId] IS NULL) OR ([RevokedAtUtc] IS NOT NULL AND [RevokedByAccountId] IS NOT NULL AND [RevokedAtUtc] >= [AssignedAtUtc])");

                            t.HasCheckConstraint("ck_access_role_assignments_timestamps", "DATEPART(TZOFFSET, [AssignedAtUtc]) = 0 AND ([RevokedAtUtc] IS NULL OR DATEPART(TZOFFSET, [RevokedAtUtc]) = 0)");

                            t.HasCheckConstraint("ck_access_role_assignments_version", "[Version] >= 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.PlatformPaymentLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("PaymentRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("PostedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<Guid>("PostedByAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransferReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentRequestId")
                        .IsUnique();

                    b.HasIndex("SchoolId", "PostedAtUtc");

                    b.HasIndex("PaymentRequestId", "TenantId", "SchoolId", "Amount", "Currency", "TransferReference");

                    b.ToTable("school_platform_payment_ledger", "billing", t =>
                        {
                            t.HasTrigger("tr_billing_payment_ledger_append_only");

                            t.HasTrigger("tr_billing_payment_ledger_approved_insert");

                            t.HasCheckConstraint("ck_billing_payment_ledger_amount", "[Amount] > 0");

                            t.HasCheckConstraint("ck_billing_payment_ledger_currency", "[Currency] COLLATE Latin1_General_BIN2 LIKE '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("ck_billing_payment_ledger_identifiers", "[Id] <> '00000000-0000-0000-0000-000000000000' AND [PaymentRequestId] <> '00000000-0000-0000-0000-000000000000' AND [PostedByAccountId] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_billing_payment_ledger_posted_utc", "DATEPART(TZOFFSET, [PostedAtUtc]) = 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.PlatformPaymentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<Guid>("RequestedByAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<Guid?>("ReviewedByAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransferReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "TransferReference")
                        .IsUnique();

                    b.HasIndex("TenantId", "SchoolId");

                    b.HasIndex("TenantId", "Status", "RequestedAtUtc");

                    b.ToTable("school_platform_payment_requests", "billing", t =>
                        {
                            t.HasTrigger("tr_billing_payment_request_approved_guard");

                            t.HasCheckConstraint("ck_billing_payment_request_amount", "[Amount] > 0");

                            t.HasCheckConstraint("ck_billing_payment_request_currency", "[Currency] COLLATE Latin1_General_BIN2 LIKE '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("ck_billing_payment_request_identifiers", "[Id] <> '00000000-0000-0000-0000-000000000000' AND [RequestedByAccountId] <> '00000000-0000-0000-0000-000000000000' AND ([ReviewedByAccountId] IS NULL OR [ReviewedByAccountId] <> '00000000-0000-0000-0000-000000000000')");

                            t.HasCheckConstraint("ck_billing_payment_request_review", "([Status] = N'Pending' AND [ReviewedByAccountId] IS NULL AND [ReviewedAtUtc] IS NULL AND [ReviewNote] IS NULL) OR ([Status] IN (N'Approved', N'Rejected') AND [ReviewedByAccountId] IS NOT NULL AND [ReviewedAtUtc] IS NOT NULL AND [ReviewedAtUtc] >= [RequestedAtUtc] AND [ReviewedByAccountId] <> [RequestedByAccountId] AND ([Status] = N'Approved' OR ([ReviewNote] IS NOT NULL AND LEN(LTRIM(RTRIM([ReviewNote]))) > 0)))");

                            t.HasCheckConstraint("ck_billing_payment_request_status", "[Status] IN (N'Pending', N'Approved', N'Rejected')");

                            t.HasCheckConstraint("ck_billing_payment_request_timestamps", "DATEPART(TZOFFSET, [RequestedAtUtc]) = 0 AND ([ReviewedAtUtc] IS NULL OR DATEPART(TZOFFSET, [ReviewedAtUtc]) = 0)");

                            t.HasCheckConstraint("ck_billing_payment_request_version", "[Version] >= 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.Units.UnitGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("PaymentMethodCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("PaymentRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("TransferOccurredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("TransferReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("UnitTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnitTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentRequestId")
                        .IsUnique();

                    b.HasIndex("SchoolId", "GrantedAtUtc");

                    b.HasIndex("PaymentRequestId", "TenantId", "SchoolId", "Amount", "Currency", "TransferReference");

                    b.HasIndex("PaymentRequestId", "TenantId", "SchoolId", "UnitTypeId", "UnitTypeCode", "UnitTypeName", "UnitPrice", "Currency", "Quantity", "Amount", "PaymentMethodCode", "TransferOccurredAtUtc");

                    b.ToTable("unit_grants", "billing", t =>
                        {
                            t.HasTrigger("tr_billing_unit_grant_append_only");

                            t.HasTrigger("tr_billing_unit_grant_approved_insert");

                            t.HasCheckConstraint("ck_billing_unit_grant_currency", "[Currency] COLLATE Latin1_General_BIN2 LIKE '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("ck_billing_unit_grant_granted_utc", "DATEPART(TZOFFSET, [GrantedAtUtc]) = 0 AND DATEPART(TZOFFSET, [TransferOccurredAtUtc]) = 0 AND [TransferOccurredAtUtc] <= [GrantedAtUtc]");

                            t.HasCheckConstraint("ck_billing_unit_grant_ids", "[Id] <> '00000000-0000-0000-0000-000000000000' AND [PaymentRequestId] <> '00000000-0000-0000-0000-000000000000' AND [UnitTypeId] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_billing_unit_grant_name", "LEN(LTRIM(RTRIM([UnitTypeName]))) > 0");

                            t.HasCheckConstraint("ck_billing_unit_grant_payment_method", "LEN([PaymentMethodCode]) BETWEEN 3 AND 40 AND [PaymentMethodCode] COLLATE Latin1_General_BIN2 = LOWER([PaymentMethodCode])");

                            t.HasCheckConstraint("ck_billing_unit_grant_price", "[UnitPrice] > 0 AND [Amount] > 0 AND [Amount] = [UnitPrice] * [Quantity]");

                            t.HasCheckConstraint("ck_billing_unit_grant_quantity", "[Quantity] BETWEEN 1 AND 1000000");

                            t.HasCheckConstraint("ck_billing_unit_grant_school", "[SchoolId] = [TenantId]");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.Units.UnitPurchaseIntent", b =>
                {
                    b.Property<Guid>("PaymentRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("PaymentMethodCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("TransferOccurredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("UnitTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnitTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("UnitTypeVersion")
                        .HasColumnType("bigint");

                    b.HasKey("PaymentRequestId");

                    b.HasIndex("UnitTypeId");

                    b.HasIndex("SchoolId", "CreatedAtUtc");

                    b.HasIndex("PaymentRequestId", "TenantId", "SchoolId", "Amount", "Currency");

                    b.ToTable("unit_purchase_intents", "billing", t =>
                        {
                            t.HasTrigger("tr_billing_unit_purchase_intent_append_only");

                            t.HasTrigger("tr_billing_unit_purchase_intent_pending_insert");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_code", "LEN([UnitTypeCode]) BETWEEN 3 AND 32 AND [UnitTypeCode] COLLATE Latin1_General_BIN2 = UPPER([UnitTypeCode])");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_created_utc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0 AND DATEPART(TZOFFSET, [TransferOccurredAtUtc]) = 0 AND [TransferOccurredAtUtc] <= [CreatedAtUtc]");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_currency", "[Currency] COLLATE Latin1_General_BIN2 LIKE '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_ids", "[PaymentRequestId] <> '00000000-0000-0000-0000-000000000000' AND [UnitTypeId] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_name", "LEN(LTRIM(RTRIM([UnitTypeName]))) > 0");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_payment_method", "LEN([PaymentMethodCode]) BETWEEN 3 AND 40 AND [PaymentMethodCode] COLLATE Latin1_General_BIN2 = LOWER([PaymentMethodCode])");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_price", "[UnitPrice] > 0 AND [Amount] > 0 AND [Amount] = [UnitPrice] * [Quantity]");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_quantity", "[Quantity] BETWEEN 1 AND 1000000");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_school", "[SchoolId] = [TenantId]");

                            t.HasCheckConstraint("ck_billing_unit_purchase_intent_version", "[UnitTypeVersion] >= 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.Units.UnitType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("unit_types", "billing", t =>
                        {
                            t.HasCheckConstraint("ck_billing_unit_type_code", "LEN([Code]) BETWEEN 3 AND 32 AND [Code] COLLATE Latin1_General_BIN2 = UPPER([Code])");

                            t.HasCheckConstraint("ck_billing_unit_type_currency", "[Currency] COLLATE Latin1_General_BIN2 LIKE '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("ck_billing_unit_type_id", "[Id] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_billing_unit_type_name", "LEN(LTRIM(RTRIM([DisplayName]))) > 0");

                            t.HasCheckConstraint("ck_billing_unit_type_price", "[UnitPrice] > 0");

                            t.HasCheckConstraint("ck_billing_unit_type_timestamps", "[CreatedAtUtc] <= [UpdatedAtUtc] AND DATEPART(TZOFFSET, [CreatedAtUtc]) = 0 AND DATEPART(TZOFFSET, [UpdatedAtUtc]) = 0");

                            t.HasCheckConstraint("ck_billing_unit_type_version", "[Version] >= 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Registry.SchoolRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("DeploymentMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ProvisioningOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegistrationRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestedByAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProvisioningOperationId")
                        .IsUnique()
                        .HasFilter("[ProvisioningOperationId] IS NOT NULL");

                    b.HasIndex("RegistrationRequestId")
                        .IsUnique();

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("schools", "registry", t =>
                        {
                            t.HasCheckConstraint("ck_registry_schools_deployment_matches_type", "[DeploymentMode] <> N'GovernmentOnPremises' OR [SchoolType] = N'Government'");

                            t.HasCheckConstraint("ck_registry_schools_deployment_mode", "[DeploymentMode] IN (N'SharedSaaS', N'DedicatedCloud', N'GovernmentOnPremises')");

                            t.HasCheckConstraint("ck_registry_schools_provisioning_operation", "([Status] IN (N'Draft', N'PendingVerification', N'Approved') AND [ProvisioningOperationId] IS NULL) OR ([Status] IN (N'Provisioning', N'ProvisioningFailed', N'Active', N'Suspended') AND [ProvisioningOperationId] IS NOT NULL AND [ProvisioningOperationId] <> '00000000-0000-0000-0000-000000000000') OR ([Status] = N'Closed' AND ([ProvisioningOperationId] IS NULL OR [ProvisioningOperationId] <> '00000000-0000-0000-0000-000000000000'))");

                            t.HasCheckConstraint("ck_registry_schools_school_is_tenant", "[Id] = [TenantId]");

                            t.HasCheckConstraint("ck_registry_schools_status", "[Status] IN (N'Draft', N'PendingVerification', N'Approved', N'Provisioning', N'ProvisioningFailed', N'Active', N'Suspended', N'Closed')");

                            t.HasCheckConstraint("ck_registry_schools_status_reason", "([Status] IN (N'ProvisioningFailed', N'Suspended', N'Closed') AND [StatusReason] IS NOT NULL AND LEN(LTRIM(RTRIM([StatusReason]))) > 0) OR ([Status] IN (N'Draft', N'PendingVerification', N'Approved', N'Provisioning', N'Active') AND [StatusReason] IS NULL)");

                            t.HasCheckConstraint("ck_registry_schools_timestamps", "[CreatedAtUtc] <= [UpdatedAtUtc] AND DATEPART(TZOFFSET, [CreatedAtUtc]) = 0 AND DATEPART(TZOFFSET, [UpdatedAtUtc]) = 0");

                            t.HasCheckConstraint("ck_registry_schools_type", "[SchoolType] IN (N'Private', N'Government')");

                            t.HasCheckConstraint("ck_registry_schools_version", "[Version] >= 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Registry.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LegalName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("tenants", "registry", t =>
                        {
                            t.HasCheckConstraint("ck_registry_tenants_status", "[Status] IN (N'Draft', N'Active', N'Suspended', N'Closed')");

                            t.HasCheckConstraint("ck_registry_tenants_status_reason", "([Status] IN (N'Suspended', N'Closed') AND [SuspensionReason] IS NOT NULL AND LEN(LTRIM(RTRIM([SuspensionReason]))) > 0) OR ([Status] IN (N'Draft', N'Active') AND [SuspensionReason] IS NULL)");

                            t.HasCheckConstraint("ck_registry_tenants_timestamps", "[CreatedAtUtc] <= [UpdatedAtUtc] AND DATEPART(TZOFFSET, [CreatedAtUtc]) = 0 AND DATEPART(TZOFFSET, [UpdatedAtUtc]) = 0");

                            t.HasCheckConstraint("ck_registry_tenants_version", "[Version] >= 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.ExternalIdentifierMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("InternalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("EntityType", "InternalId");

                    b.HasIndex("SourceSystem", "EntityType", "ExternalId")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NULL");

                    b.HasIndex("TenantId", "SourceSystem", "EntityType", "ExternalId")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NOT NULL");

                    b.ToTable("external_id_mappings", "registry", t =>
                        {
                            t.HasCheckConstraint("ck_registry_external_id_mappings_created_utc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "OccurredAtUtc");

                    b.HasIndex("ResourceType", "ResourceId");

                    b.HasIndex("TenantId", "OccurredAtUtc");

                    b.ToTable("audit_entries", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_operations_audit_entries_occurred_utc", "DATEPART(TZOFFSET, [OccurredAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformFeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NULL");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NOT NULL");

                    b.ToTable("feature_flags", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_operations_feature_flags_timestamps", "[CreatedAtUtc] <= [UpdatedAtUtc] AND DATEPART(TZOFFSET, [CreatedAtUtc]) = 0 AND DATEPART(TZOFFSET, [UpdatedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformInboxMessage", b =>
                {
                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.HasKey("Consumer", "MessageId");

                    b.HasIndex("ProcessedAtUtc", "ReceivedAtUtc")
                        .HasFilter("[ProcessedAtUtc] IS NULL");

                    b.ToTable("inbox_messages", "messaging", t =>
                        {
                            t.HasCheckConstraint("ck_messaging_platform_inbox_timestamps", "DATEPART(TZOFFSET, [ReceivedAtUtc]) = 0 AND ([ProcessedAtUtc] IS NULL OR ([ProcessedAtUtc] >= [ReceivedAtUtc] AND DATEPART(TZOFFSET, [ProcessedAtUtc]) = 0))");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<int>("FailedSignInCount")
                        .HasColumnType("int");

                    b.Property<string>("HashingAlgorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HashingVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("local_credentials", "access", t =>
                        {
                            t.HasCheckConstraint("ck_access_local_credentials_failed_count", "[FailedSignInCount] >= 0");

                            t.HasCheckConstraint("ck_access_local_credentials_hashing_version", "[HashingVersion] > 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("local_users", "access", t =>
                        {
                            t.HasCheckConstraint("ck_access_local_users_identifiers", "[Id] <> '00000000-0000-0000-0000-000000000000' AND [PersonId] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_access_local_users_status", "[Status] IN (N'PendingActivation', N'Active', N'Disabled')");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc")
                        .HasFilter("[ProcessedAtUtc] IS NULL");

                    b.ToTable("outbox_messages", "messaging", t =>
                        {
                            t.HasCheckConstraint("ck_messaging_platform_outbox_timestamps", "DATEPART(TZOFFSET, [OccurredAtUtc]) = 0 AND ([ProcessedAtUtc] IS NULL OR ([ProcessedAtUtc] >= [OccurredAtUtc] AND DATEPART(TZOFFSET, [ProcessedAtUtc]) = 0)) AND ([NextAttemptAtUtc] IS NULL OR ([NextAttemptAtUtc] >= [OccurredAtUtc] AND DATEPART(TZOFFSET, [NextAttemptAtUtc]) = 0))");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformPermissionRecord", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Code");

                    b.ToTable("permissions", "access");

                    b.HasData(
                        new
                        {
                            Code = "platform.schools.read"
                        },
                        new
                        {
                            Code = "platform.schools.manage"
                        },
                        new
                        {
                            Code = "platform.schools.activate"
                        },
                        new
                        {
                            Code = "platform.access.manage"
                        },
                        new
                        {
                            Code = "platform.billing.read"
                        },
                        new
                        {
                            Code = "platform.billing.manage"
                        },
                        new
                        {
                            Code = "platform.payments.approve"
                        },
                        new
                        {
                            Code = "platform.support.manage"
                        },
                        new
                        {
                            Code = "platform.deployments.manage"
                        },
                        new
                        {
                            Code = "platform.audit.read"
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformRolePermissionRecord", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId", "PermissionCode");

                    b.HasIndex("PermissionCode");

                    b.ToTable("role_permissions", "access");
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformSmsLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("MessageEncrypted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecipientEncrypted")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RecipientMasked")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ResponseEncrypted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ProviderId", "CreatedAtUtc");

                    b.HasIndex("SourceSystem", "SourceMessageId")
                        .IsUnique()
                        .HasFilter("[SourceMessageId] IS NOT NULL");

                    b.HasIndex("SourceSystem", "SchoolId", "CreatedAtUtc");

                    b.ToTable("sms_logs", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_platform_sms_logs_completion", "([Status] = 'Pending' AND [CompletedAtUtc] IS NULL) OR ([Status] <> 'Pending' AND [CompletedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("ck_platform_sms_logs_http_status", "[HttpStatusCode] IS NULL OR [HttpStatusCode] BETWEEN 100 AND 599");

                            t.HasCheckConstraint("ck_platform_sms_logs_school_scope", "[SourceSystem] <> 'schools' OR [SchoolId] IS NOT NULL");

                            t.HasCheckConstraint("ck_platform_sms_logs_source_system", "[SourceSystem] IN ('platform', 'schools', 'family')");

                            t.HasCheckConstraint("ck_platform_sms_logs_status", "[Status] IN ('Pending', 'Accepted', 'Rejected', 'Failed')");

                            t.HasCheckConstraint("ck_platform_sms_logs_timestamps", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0 AND ([CompletedAtUtc] IS NULL OR ([CompletedAtUtc] >= [CreatedAtUtc] AND DATEPART(TZOFFSET, [CompletedAtUtc]) = 0))");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformSmsProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiUrlTemplate")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MessageCharactersLength")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ProviderUserName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SuccessResponsePrefix")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted", "IsActive", "Priority");

                    b.ToTable("sms_providers", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_platform_sms_providers_api_url_https", "[ApiUrlTemplate] LIKE 'https://%'");

                            t.HasCheckConstraint("ck_platform_sms_providers_deleted_inactive", "[IsDeleted] = 0 OR [IsActive] = 0");

                            t.HasCheckConstraint("ck_platform_sms_providers_message_length", "[MessageCharactersLength] BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("ck_platform_sms_providers_priority", "[Priority] >= 1");

                            t.HasCheckConstraint("ck_platform_sms_providers_timestamps", "[CreatedAtUtc] <= [UpdatedAtUtc] AND DATEPART(TZOFFSET, [CreatedAtUtc]) = 0 AND DATEPART(TZOFFSET, [UpdatedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Access.PlatformRoleAssignment", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Access.PlatformRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.PlatformPaymentLedgerEntry", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Billing.PlatformPaymentRequest", null)
                        .WithMany()
                        .HasForeignKey("PaymentRequestId", "TenantId", "SchoolId", "Amount", "Currency", "TransferReference")
                        .HasPrincipalKey("Id", "TenantId", "SchoolId", "Amount", "Currency", "TransferReference")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.PlatformPaymentRequest", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Registry.SchoolRegistration", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SchoolId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.Units.UnitGrant", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Billing.PlatformPaymentRequest", null)
                        .WithMany()
                        .HasForeignKey("PaymentRequestId", "TenantId", "SchoolId", "Amount", "Currency", "TransferReference")
                        .HasPrincipalKey("Id", "TenantId", "SchoolId", "Amount", "Currency", "TransferReference")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mdaresna.Platform.Domain.Billing.Units.UnitPurchaseIntent", null)
                        .WithMany()
                        .HasForeignKey("PaymentRequestId", "TenantId", "SchoolId", "UnitTypeId", "UnitTypeCode", "UnitTypeName", "UnitPrice", "Currency", "Quantity", "Amount", "PaymentMethodCode", "TransferOccurredAtUtc")
                        .HasPrincipalKey("PaymentRequestId", "TenantId", "SchoolId", "UnitTypeId", "UnitTypeCode", "UnitTypeName", "UnitPrice", "Currency", "Quantity", "Amount", "PaymentMethodCode", "TransferOccurredAtUtc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Billing.Units.UnitPurchaseIntent", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Billing.Units.UnitType", null)
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mdaresna.Platform.Domain.Billing.PlatformPaymentRequest", null)
                        .WithMany()
                        .HasForeignKey("PaymentRequestId", "TenantId", "SchoolId", "Amount", "Currency")
                        .HasPrincipalKey("Id", "TenantId", "SchoolId", "Amount", "Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdaresna.Platform.Domain.Registry.SchoolRegistration", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Registry.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.ExternalIdentifierMapping", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Registry.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformFeatureFlag", b =>
                {
                    b.HasOne("Mdaresna.Platform.Domain.Registry.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalCredential", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalUser", "User")
                        .WithOne("Credential")
                        .HasForeignKey("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformRolePermissionRecord", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformPermissionRecord", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mdaresna.Platform.Domain.Access.PlatformRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformSmsLog", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformSmsProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Platform.Entities.PlatformLocalUser", b =>
                {
                    b.Navigation("Credential");
                });
#pragma warning restore 612, 618
        }
    }
}
