// <auto-generated />
using System;
using Mdaresna.Platform.Infrastructure.Persistence.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mdaresna.Platform.Infrastructure.Persistence.Identity.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260914180603_AddSupplementaryAccountContacts")]
    partial class AddSupplementaryAccountContacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GenderCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PreferredLocale")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("accounts", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_identity_accounts_status", "[Status] IN (N'PendingVerification', N'Active', N'Locked', N'Disabled')");

                            t.HasCheckConstraint("ck_identity_accounts_timestamps", "[CreatedAtUtc] <= [UpdatedAtUtc] AND DATEPART(TZOFFSET, [CreatedAtUtc]) = 0 AND DATEPART(TZOFFSET, [UpdatedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.AccountActivationChallenge", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastSentAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SendCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SendWindowStartUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.HasKey("AccountId");

                    b.ToTable("account_activation_challenges", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_identity_activation_challenge_counts", "[SendCount] >= 0 AND [FailedAttempts] >= 0");

                            t.HasCheckConstraint("ck_identity_activation_challenge_expiry", "[ExpiresAtUtc] > [CreatedAtUtc]");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.AccountAppLanguagePreference", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.HasKey("AccountId", "AppCode");

                    b.ToTable("account_app_language_preferences", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_identity_app_language_app_code", "[AppCode] IN (N'platform', N'schools', N'family')");

                            t.HasCheckConstraint("ck_identity_app_language_language_code", "[LanguageCode] IN (N'ar', N'en')");

                            t.HasCheckConstraint("ck_identity_app_language_updated_at_utc", "DATEPART(TZOFFSET, [UpdatedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.AccountContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId", "Type", "NormalizedValue")
                        .IsUnique()
                        .HasFilter("[Type] IN (N'Phone', N'Email')");

                    b.ToTable("account_contacts", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_identity_account_contacts_type", "[Type] IN (N'Phone', N'Email', N'Address')");

                            t.HasCheckConstraint("ck_identity_account_contacts_value", "[Value] <> N'' AND [NormalizedValue] <> N''");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.AccountPasswordResetChallenge", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastSentAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SendCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SendWindowStartUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.HasKey("AccountId");

                    b.ToTable("account_password_reset_challenges", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_identity_password_reset_challenge_counts", "[SendCount] >= 0 AND [FailedAttempts] >= 0");

                            t.HasCheckConstraint("ck_identity_password_reset_challenge_expiry", "[ExpiresAtUtc] > [CreatedAtUtc]");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.IdentityOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc")
                        .HasFilter("[ProcessedAtUtc] IS NULL");

                    b.ToTable("outbox_messages", "messaging", t =>
                        {
                            t.HasCheckConstraint("ck_messaging_identity_outbox_nullable_utc", "([ProcessedAtUtc] IS NULL OR DATEPART(TZOFFSET, [ProcessedAtUtc]) = 0) AND ([NextAttemptAtUtc] IS NULL OR DATEPART(TZOFFSET, [NextAttemptAtUtc]) = 0)");

                            t.HasCheckConstraint("ck_messaging_identity_outbox_occurred_utc", "DATEPART(TZOFFSET, [OccurredAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.IdentitySecurityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "OccurredAtUtc");

                    b.HasIndex("EventType", "OccurredAtUtc");

                    b.ToTable("security_events", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_identity_security_events_occurred_utc", "DATEPART(TZOFFSET, [OccurredAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.IdentitySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("ReplacedBySessionId")
                        .IsUnique()
                        .HasFilter("[ReplacedBySessionId] IS NOT NULL");

                    b.HasIndex("AccountId", "ExpiresAtUtc");

                    b.HasIndex("AccountId", "ReplacedBySessionId");

                    b.ToTable("sessions", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_identity_sessions_expiry", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("ck_identity_sessions_replacement_not_self", "[ReplacedBySessionId] IS NULL OR [ReplacedBySessionId] <> [Id]");

                            t.HasCheckConstraint("ck_identity_sessions_replacement_requires_revocation", "[ReplacedBySessionId] IS NULL OR [RevokedAtUtc] IS NOT NULL");

                            t.HasCheckConstraint("ck_identity_sessions_timestamps", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0 AND DATEPART(TZOFFSET, [ExpiresAtUtc]) = 0 AND ([LastSeenAtUtc] IS NULL OR ([LastSeenAtUtc] >= [CreatedAtUtc] AND DATEPART(TZOFFSET, [LastSeenAtUtc]) = 0)) AND ([RevokedAtUtc] IS NULL OR ([RevokedAtUtc] >= [CreatedAtUtc] AND DATEPART(TZOFFSET, [RevokedAtUtc]) = 0))");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.LoginIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("DisplayValue")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Type", "NormalizedValue")
                        .IsUnique()
                        .HasFilter("[SchoolId] IS NULL");

                    b.HasIndex("SchoolId", "Type", "NormalizedValue")
                        .IsUnique()
                        .HasFilter("[SchoolId] IS NOT NULL");

                    b.ToTable("login_identifiers", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_identity_login_identifiers_scope", "([Type] IN (N'Email', N'Phone') AND [SchoolId] IS NULL) OR ([Type] IN (N'SchoolUsername', N'StudentCode') AND [SchoolId] IS NOT NULL)");

                            t.HasCheckConstraint("ck_identity_login_identifiers_timestamps", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0 AND ([VerifiedAtUtc] IS NULL OR ([VerifiedAtUtc] >= [CreatedAtUtc] AND DATEPART(TZOFFSET, [VerifiedAtUtc]) = 0))");

                            t.HasCheckConstraint("ck_identity_login_identifiers_verification", "([IsVerified] = 1 AND [VerifiedAtUtc] IS NOT NULL) OR ([IsVerified] = 0 AND [VerifiedAtUtc] IS NULL)");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.MfaMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("DestinationHint")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecretReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1 AND [IsEnabled] = 1");

                    b.HasIndex("AccountId", "Type");

                    b.ToTable("mfa_methods", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_identity_mfa_methods_authenticator_secret", "[Type] <> N'Authenticator' OR ([SecretReference] IS NOT NULL AND LEN(LTRIM(RTRIM([SecretReference]))) > 0)");

                            t.HasCheckConstraint("ck_identity_mfa_methods_primary_enabled", "[IsPrimary] = 0 OR [IsEnabled] = 1");

                            t.HasCheckConstraint("ck_identity_mfa_methods_timestamps", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0 AND ([LastUsedAtUtc] IS NULL OR ([LastUsedAtUtc] >= [CreatedAtUtc] AND DATEPART(TZOFFSET, [LastUsedAtUtc]) = 0))");

                            t.HasCheckConstraint("ck_identity_mfa_methods_type", "[Type] IN (N'Authenticator', N'Email', N'Sms')");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.PasswordCredential", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<int>("FailedSignInCount")
                        .HasColumnType("int");

                    b.Property<string>("HashingAlgorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HashingVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AccountId");

                    b.ToTable("password_credentials", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_identity_password_credentials_failed_count", "[FailedSignInCount] >= 0");

                            t.HasCheckConstraint("ck_identity_password_credentials_hashing_version", "[HashingVersion] > 0");

                            t.HasCheckConstraint("ck_identity_password_credentials_timestamps", "DATEPART(TZOFFSET, [ChangedAtUtc]) = 0 AND ([LockoutEndUtc] IS NULL OR DATEPART(TZOFFSET, [LockoutEndUtc]) = 0)");
                        });
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.AccountActivationChallenge", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.Account", "Account")
                        .WithOne("ActivationChallenge")
                        .HasForeignKey("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.AccountActivationChallenge", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.AccountAppLanguagePreference", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.Account", "Account")
                        .WithMany("AppLanguagePreferences")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.AccountContact", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.Account", "Account")
                        .WithMany("Contacts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.AccountPasswordResetChallenge", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.Account", "Account")
                        .WithOne("PasswordResetChallenge")
                        .HasForeignKey("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.AccountPasswordResetChallenge", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.IdentitySession", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.Account", "Account")
                        .WithMany("Sessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.IdentitySession", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "ReplacedBySessionId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.LoginIdentifier", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.Account", "Account")
                        .WithMany("LoginIdentifiers")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.MfaMethod", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.Account", "Account")
                        .WithMany("MfaMethods")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.PasswordCredential", b =>
                {
                    b.HasOne("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.Account", "Account")
                        .WithOne("PasswordCredential")
                        .HasForeignKey("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.PasswordCredential", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Mdaresna.Platform.Infrastructure.Persistence.Identity.Entities.Account", b =>
                {
                    b.Navigation("ActivationChallenge");

                    b.Navigation("AppLanguagePreferences");

                    b.Navigation("Contacts");

                    b.Navigation("LoginIdentifiers");

                    b.Navigation("MfaMethods");

                    b.Navigation("PasswordCredential");

                    b.Navigation("PasswordResetChallenge");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
